### ISSUE TITLE
Allow import of ANM

### ISSUE THREAD

**Issue by lispascal** [lispascal/lolblender#16]
Already in progress, but figured I'd put an issue up.

**Comment by lispascal** [comment]
In progress of this, it has been revealed that #14 is not quite done, and that even SKL v1-2 aren't imported -quite- correctly, I think

**Comment by Treehee** [comment]
I was wondering how far the progress on this issue is, as it is fairly important for map skins ^^

**Comment by lispascal** [comment]
Unfortunately, I was not able to figure out the format for .ANM (animation) files. I tried a whole bunch of different approaches for applying the .ANM to the skeletons, but could not figure it out at that time.

This stuff is somewhat complicated if you do not already know what the parts are, and is further complicated by multiple version formats as League continues to be developed (v0-v4, 5 formats, was the count at about 2 years ago). A description of how the .ANM files are formatted/how their animations were applied to skeletons would be Extremely helpful, since figuring that out is the majority of the work for this issue. I think possibly some of the other developers of League related tools (wooxy, etc) might have this kind of knowledge/information, since I know they do render some of them, but I have not communicated with them about it.

Alternatively, if there's a very small (few parts) skeleton, with a known tiny/short animation, it may be possible with a lot of work to figure out at least one of the version formats, through a lot of trial and error.

Finally, it is possible that a person could dig through League's code/disassemble it to figure out how it uses the animation files, but that is a huge amount of work, and frankly, I do not even have League installed anymore.

Sorry for the bad news, but I am unlikely to work on this due to the reasons outlined above.

**Comment by Treehee** [comment]
I did find another project (written is C++) that converts League files to dae (including anm files). Maybe you can do some decompiling and researching of its code?
https://code.google.com/archive/p/lol2dae/

**Comment by Treehee** [comment]
If I have the time I'll do some digging in League ^^

**Comment by cschar** [comment]
@Treehee  i'd be cool if you could merge loldae wrapped up via a python c/c++ extension into this project!

**Comment by Treehee** [comment]
@cschar I don't think I have enough knowledge of either language to do that. Besides, .dae is still not what you'd want as an end result, as it doesn't handle multiple animations on one mesh. It's more useful for studying .anm files.

Also, after talking with some members of the community (mostly Uri), I found out Riot is switching to a new filetype, .WAD. .WAD is a signed filetype, meaning we can't edit them (or at least not customize them in-game). It will contain both mesh and animation data.

**Comment by Crauzer** [comment]
https://github.com/LoL-Fantome/Fantome.Libraries.League
https://github.com/Crauzer/Flow
https://github.com/Crauzer/Obsidian

Here's your full package to edit them @Treehee

**Comment by Crauzer** [comment]
Also if you guys want a documentation of CANM Animation files (The ones which are the newest), I could provide one since I already know most of the structure, just need to figure out some unknown stuff in the header. The structure is pretty similiar to the older ANM files, it has 48 bit compressed Quaternions

**Comment by Treehee** [comment]
As I said, WAD files arew signed, meaning you don't mod them in your game. You can open them, sure, but if you edit them they won't work in League.

**Comment by Crauzer** [comment]
Signature can be bypassed, I already did it and got a working skin with WAD into the game.

[Ornn Edit](https://i.imgur.com/Fbuc5ly.png)
[Katarina Edit](https://www.youtube.com/watch?v=D1qrFdqjc5o)

**Comment by Crauzer** [comment]
I've also talked with Rio about this and how they're going to change their game structure, RADS will be completely replaced by WAD.
They told me to withdraw my tools as it can get people banned if it is detected, funny thing, they have no way of detecting my mods yet, I don't change the executable size meaning that a check for it won't work, and as far as I know they don't checksum the executable before starting it

**Comment by Treehee** [comment]
I don't think we should get in a conflict with Riot.

**Comment by lispascal** [comment]
Feel free to fork this project to make your own changes. I'll even link it in the README of this repo. I personally am not interested in circumventing more of Riot's protections, or even reinstalling League to get the files to work on this with.

Cheers
