### ISSUE TITLE
Texture not applied

### ISSUE THREAD

**Issue by denneboomyo** [lispascal/lolblender#18]
The texture of a skin is not applied to the model.

**Comment by lispascal** [comment]
This is not yet set to be done automatically. I'll work on this soon.

At the moment, the workaround is as follows:
1. Import your files (at least .skn and .dds). Set your 3D view Viewport shading to Texture.
2. In Object Mode, select the Mesh object (not the armature). Hit tab to go into Edit Mode.
3. In UV/Image Editor pane, click the image to the left of the texture file name (with hover text "Browse Image to be linked"), and click on the file name in that pop-up.
4. For full lighting, delete the Lamp object from the scene.

Note that this only works with Blender Render at the moment.

**Comment by lispascal** [comment]
The model will now be automatically textured by a material, as noted in 
339f88e721a0c30848f56ba5c6b698a6f8da9115. To see it, just set your 3d-view ViewPort Shade (to the right of the Object Mode spot) to "Material". 

Thank you for the notice, @denneboomyo . Feel free to reopen this issue or open a new one if you encounter any problems.
