### ISSUE TITLE
The addon is not installing aparently :[

### ISSUE THREAD

**Issue by Mediocorite** [lispascal/lolblender#20]
I'm running the latest version of blender on ubuntu 14.04 (xfce) and i tried manually placing the files in the directory /usr/lib/blender/scripts/addon and also importing from the zip. The addon still failed to show up when i typed "league" or "League" or even "export"/"import".
Please help

**Comment by lispascal** [comment]
@Mediocorite Did you copy the whole folder io_scene_lol into that directory, and nothing more? If you copied the whole branch (ie: the lolblender-master folder) it will not detect it.

**Comment by Mediocorite** [comment]
Sorry to get back to you so late.
I copied the io_scene_lol folder alone to the directory /usr/lib/blender/scripts/addons/ as stated in this thread http://askubuntu.com/questions/144766/where-does-blender-install-on-ubuntu ,
After that i started blender and tried searching for the addon but it won't detect.

**Comment by Mediocorite** [comment]
I have now installed the plugin in a windows computer. It seems the issue was on my end :/
Sorry to disturb you.

**Comment by lispascal** [comment]
It's not a problem. Thank you for your patience, and I am glad you found a solution.

Additionally, if you are still trying on Ubuntu, that same link has a comment saying it could also be in  /usr/share/blender/scripts/addons/

**Comment by Mediocorite** [comment]
Yes that was the issue. Thank you so much.
