### ISSUE TITLE
Patch for /trunk/io_scene_lol/__bpy_init__.py

### ISSUE THREAD

**Issue by GoogleCodeExporter** [lispascal/lolblender#4]
```
Making it compatible for blender 2.57
```

Original issue reported on code.google.com by `avithan@gmail.com` on 12 Jun 2011 at 11:42

Attachments:
* [__bpy_init__.py.patch](https://storage.googleapis.com/google-code-attachments/lolblender/issue-4/comment-0/__bpy_init__.py.patch)

**Comment by lispascal** [comment]
see #13
