### ISSUE TITLE
About bone index

### ISSUE THREAD

**Issue by GoogleCodeExporter** [lispascal/lolblender#6]
```
Hi~

I don't understand how bone index works?~one vertex has 4 bone index?
How can i build the model with bone?
```

Original issue reported on code.google.com by `406...@gmail.com` on 15 Jun 2012 at 2:37

**Comment by lispascal** [comment]
The 4 bone indices indicate the "weight" of the bone to that vertex. In other words, movement of the bones referred to by those indices will influence the position of the vertex
